### PR TITLE
Enabled restart policy for all containers

### PR DESCRIPTION
**Pull request by Seikilos**
Inconsistent compose file fixed because a reboot started some but not all containers.

### CODE REVIEW

**Comment by wrn14897** [comment]
Thanks for the contribution! I'd suggest to set the restart policy to `on-failure` for long running process. only the short lifecycle processes like `task-check-alerts` have `always` policy

**Comment by Seikilos** [comment]
> Thanks for the contribution! I'd suggest to set the restart policy to `on-failure` for long running process. only the short lifecycle processes like `task-check-alerts` have `always` policy

Works for me. My motivation to change the default compose file was: When I (accidently) restarted the machine, I noticed hyperdx no longer working. When I ran `docker ps` there were only a couple of hyperdx processes started, others were not. Then I started digging through logs of those exited containers to understand what was wrong, but did not find anything.
I think this is a bit of inconsistent behaviour, I would expect all being off, or all being on and working.
What is your opinion in such a scenario?

**Comment by wrn14897** [comment]
> > Thanks for the contribution! I'd suggest to set the restart policy to `on-failure` for long running process. only the short lifecycle processes like `task-check-alerts` have `always` policy
> 
> Works for me. My motivation to change the default compose file was: When I (accidently) restarted the machine, I noticed hyperdx no longer working. When I ran `docker ps` there were only a couple of hyperdx processes started, others were not. Then I started digging through logs of those exited containers to understand what was wrong, but did not find anything. I think this is a bit of inconsistent behaviour, I would expect all being off, or all being on and working. What is your opinion in such a scenario?



> > Thanks for the contribution! I'd suggest to set the restart policy to `on-failure` for long running process. only the short lifecycle processes like `task-check-alerts` have `always` policy
> 
> Works for me. My motivation to change the default compose file was: When I (accidently) restarted the machine, I noticed hyperdx no longer working. When I ran `docker ps` there were only a couple of hyperdx processes started, others were not. Then I started digging through logs of those exited containers to understand what was wrong, but did not find anything. I think this is a bit of inconsistent behaviour, I would expect all being off, or all being on and working. What is your opinion in such a scenario?

Great question. The `on-failure` should cover the normal exit case (like daemon restart). The reason to stop with non-zero exit code is because the service might be in a bad state that we want to diagnose the issue first. I think its safe to set
1. db related services to `on-failure` (`db`, `ch-server`, `redis`)
2. app + ingestion services to `unless-stopped` (`api`, `app`, `miner`, `go-parser`, `otel-collector`, `aggregator`, `ingestor`)
3. non essential or cron task services to `always` (`task-check-alerts`, `hostmetrics`)

We will revisit the policy again. But I think this is a good start 💪

**Comment by Seikilos** [comment]
On hold. Currently lack of resources to pursue this.

**Pull request closed without merging**
