### PR TITLE
Add Hyperdx helm chart

### PR DESCRIPTION
**Pull request by anjiann**

### CODE REVIEW

**Comment by momenthana** [comment]
@anjiann It seems like it hasn't merged for a long time due to something else.
you separate the helm chart part and provide this like the https://github.com/pintoinc/hyperdx-helm repository.
make a hyperdx-helm? I need a helm chart!

**Comment by lazyoldbear** [comment]
So, about this. 
What about this?

**Comment by ttj4** [comment]
what happened to this PR? If you need someone else to pick it and do a rebase, I happy to help

**Comment by MikeShi42** [comment]
Hey everyone, sorry we've been quiet on this PR. We've made a number of attempts at getting this PR reviewed internally and I've personally been hopeful we could get this PR merged each time. Unfortunately, the PR length/complexity makes it difficult for us to review - and additionally it gives us a lot of concern in our ability to support/maintain it properly, especially as we will not be using this Helm chart ourselves in regular development/testing/deployment.

We're more than happy to assist in a community-maintained version, something like what @momenthana has put together (I assume based off of this PR, which we're really grateful for you putting together @anjiann) at https://github.com/pintoinc/hyperdx-helm.

Apologies for not being able to get this officially supported and taking a while for us to hit this conclusion. In the future, we may be able to figure out a way to incorporate maintaining a Helm chart or an "official community-maintained" repo of resources that can include this chart as well. For now, I'm going to close out this PR, we'll likely start pointing people towards that existing repo, and continue any other relevant discussion at #74.

**Pull request closed without merging**
