### PR TITLE
fix: control logs telemetry using `HYPERDX_LOG_LEVEL`

### PR DESCRIPTION
**Pull request by wrn14897**

### CODE REVIEW

**Review by MikeShi42 — APPROVED** [review]
lgtm, looks like vector's CDN is breaking our CI though

**Comment by wrn14897** [comment]
> lgtm, looks like vector's CDN is breaking our CI though

Noticed this. Hopefully it gets fixed soon.

**Comment by Seikilos** [comment]
@MikeShi42 what is exactly breaking for you? I had issues to build the image on our company network due to blacklisted domains.

**Comment by wrn14897** [comment]
> @MikeShi42 what is exactly breaking for you? I had issues to build the image on our company network due to blacklisted domains.

It's the vector installation script used in github action CI. I think it's not related. Have the issues with the blacklisted domains been resolved ?

**Comment by Seikilos** [comment]
> > @MikeShi42 what is exactly breaking for you? I had issues to build the image on our company network due to blacklisted domains.
> 
> It's the vector installation script used in github action CI. I think it's not related. Have the issues with the blacklisted domains been resolved ?

Had to rebuilt the custom image at home and push it to githubs artifact repo, from where I could download it 😐. Can't even access github codespaces from work.
So far I have a working on prem hyperdx and will start sending data when I figured out how to instrument our source properly :)

I am very curious to feed it some real world data!

**Comment by MikeShi42** [comment]
@Seikilos any chance you'd be open to opening an issue about the blocked domains? Wonder if it's a recurring issue we can at least keep an eye on (and collect more feedback about) if we can't fix in the near term.

**Comment by Seikilos** [comment]
> @Seikilos any chance you'd be open to opening an issue about the blocked domains? Wonder if it's a recurring issue we can at least keep an eye on (and collect more feedback about) if we can't fix in the near term.

Our proxy on our company network started to block all access to CDNs and every url not whitelisted. I am not sure, whether you actually want to track that. We can get a CDN url whitelisted but only for fully qualified urls without wildcards. While I sort of understand the security intention behind it, it makes developing software "less" than ideal.

**Pull request merged**
